version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Map the container's port to host
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=email_management
    depends_on:
      - mysql
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Expose frontend on port 80
    depends_on:
      - backend
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: email_management
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
