# docker-compose.yml (Final Version with Traefik)
version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=jeet.patel1031r2005@gmail.com" # 👈 Change this
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # For Traefik Dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Rangtech@01
      - DB_NAME=email_management
    depends_on:
      - mysql
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    restart: always
    # ❌ Port is no longer needed here. Traefik handles it.
    labels: # 👈 ADD THIS SECTION
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`eapp.mictominds.com`)" # 👈 Change this
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=Host(`eapp.mictominds.com`)" # 👈 Change this
      - "traefik.http.routers.web.middlewares=redirect"
    depends_on:
      - backend
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rangtech@01
      MYSQL_DATABASE: email_management
    volumes:
      - mysql_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: